apiVersion: apps/v1
kind: Deployment
metadata:
  name: asus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asus
  template:
    metadata:
      labels:
        app: asus
    spec:
      containers:
      - image: okteto.dev/asus:latest
        name: asus
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "946986b2-6f3e-4279-bb62-99b1a4a2b1c6"
        - name: Vless_Path
          value: "/79tg3sg3"
        - name: Vmess_UUID
          value: "946986b2-6f3e-4279-bb62-99b1a4a2b1c6"
        - name: Vmess_Path
          value: "/63wrfede3"
        - name: Share_Path
          value: "/share233"
