apiVersion: apps/v1
kind: Deployment
metadata:
  name: dell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dell
  template:
    metadata:
      labels:
        app: dell
    spec:
      containers:
      - image: okteto.dev/dell:latest
        name: dell
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "a4ee2fd1-8b47-4563-bb68-2945d58a8939"
        - name: Vless_Path
          value: "/Nou85ds"
        - name: Vmess_UUID
          value: "a4ee2fd1-8b47-4563-bb68-2945d58a8939"
        - name: Vmess_Path
          value: "/B9fs34d"
        - name: Share_Path
          value: "/share233"
