apiVersion: apps/v1
kind: Deployment
metadata:
  name: bay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bay
  template:
    metadata:
      labels:
        app: bay
    spec:
      containers:
      - image: okteto.dev/bay:latest
        name: bay
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "93670134-8249-4937-a399-c276ad29c079"
        - name: Vless_Path
          value: "/79rhfed"
        - name: Vmess_UUID
          value: "93670134-8249-4937-a399-c276ad29c079"
        - name: Vmess_Path
          value: "/7y4tefss3"
        - name: Share_Path
          value: "/share233"
