apiVersion: apps/v1
kind: Deployment
metadata:
  name: hty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hty
  template:
    metadata:
      labels:
        app: hty
    spec:
      containers:
      - image: okteto.dev/hty:latest
        name: hty
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "fc22b800-cd83-47dd-aa10-b8ba596a9968"
        - name: Vless_Path
          value: "/Mo08js"
        - name: Vmess_UUID
          value: "fc22b800-cd83-47dd-aa10-b8ba596a9968"
        - name: Vmess_Path
          value: "/Shgd4v"
        - name: Share_Path
          value: "/share233"
