apiVersion: apps/v1
kind: Deployment
metadata:
  name: inq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inq
  template:
    metadata:
      labels:
        app: inq
    spec:
      containers:
      - image: okteto.dev/inq:latest
        name: inq
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "6e6057fc-862e-4b04-b6fd-0ef9c7ec553f"
        - name: Vless_Path
          value: "/No9w3gd"
        - name: Vmess_UUID
          value: "6e6057fc-862e-4b04-b6fd-0ef9c7ec553f"
        - name: Vmess_Path
          value: "/F68rfee"
        - name: Share_Path
          value: "/share233"
