apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray
  template:
    metadata:
      labels:
        app: ray
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: ray
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "https://icook.tw"
        - name: Vless_UUID
          value: "6f1f47ec-21de-4288-b115-17478890a4ca"
        - name: Vless_Path
          value: "/b38f58b5-a1b4-4f06-9891-de87d2b4d1b8"
        - name: Vmess_UUID
          value: "6f1f47ec-21de-4288-b115-17478890a4ca"
        - name: Vmess_Path
          value: "/54bd162a-cdb6-453c-a453-4e2792bf4c17"
        - name: Share_Path
          value: "/share233"
