apiVersion: apps/v1
kind: Deployment
metadata:
  name: les
spec:
  replicas: 1
  selector:
    matchLabels:
      app: les
  template:
    metadata:
      labels:
        app: les
    spec:
      containers:
      - image: okteto.dev/les:latest
        name: les
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "46915cb1-fe29-4af3-ab44-049340bde7de"
        - name: Vless_Path
          value: "/9oyfcw3"
        - name: Vmess_UUID
          value: "46915cb1-fe29-4af3-ab44-049340bde7de"
        - name: Vmess_Path
          value: "/iuhgd3g"
        - name: Share_Path
          value: "/share233"
