apiVersion: apps/v1
kind: Deployment
metadata:
  name: etc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etc
  template:
    metadata:
      labels:
        app: etc
    spec:
      containers:
      - image: okteto.dev/etc:latest
        name: etc
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "67a3b154-5f90-4b6c-967e-8a3c8c2ef2cf"
        - name: Vless_Path
          value: "/87trdv"
        - name: Vmess_UUID
          value: "67a3b154-5f90-4b6c-967e-8a3c8c2ef2cf"
        - name: Vmess_Path
          value: "/09876yrf3"
        - name: Share_Path
          value: "/share233"
