apiVersion: apps/v1
kind: Deployment
metadata:
  name: meuz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meuz
  template:
    metadata:
      labels:
        app: meuz
    spec:
      containers:
      - image: okteto.dev/meuz:latest
        name: meuz
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "b678e32b-aecb-4b68-8079-9417f13f9c51"
        - name: Vless_Path
          value: "/SvMm244233"
        - name: Vmess_UUID
          value: "b678e32b-aecb-4b68-8079-9417f13f9c51"
        - name: Vmess_Path
          value: "/SvMm244244"
        - name: Share_Path
          value: "/share233"
