apiVersion: apps/v1
kind: Deployment
metadata:
  name: oppo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oppo
  template:
    metadata:
      labels:
        app: oppo
    spec:
      containers:
      - image: okteto.dev/oppo:latest
        name: oppo
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "e526cf64-b728-4171-9143-b529988700e1"
        - name: Vless_Path
          value: "/uiom34fw"
        - name: Vmess_UUID
          value: "e526cf64-b728-4171-9143-b529988700e1"
        - name: Vmess_Path
          value: "/urh353ds2"
        - name: Share_Path
          value: "/share233"
