apiVersion: apps/v1
kind: Deployment
metadata:
  name: ting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ting
  template:
    metadata:
      labels:
        app: ting
    spec:
      containers:
      - image: okteto.dev/ting:latest
        name: ting
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "e363d6aa-6474-4e50-8bbf-3c07ba3ce145"
        - name: Vless_Path
          value: "/SvMm244233"
        - name: Vmess_UUID
          value: "e363d6aa-6474-4e50-8bbf-3c07ba3ce145"
        - name: Vmess_Path
          value: "/SvMm244244"
        - name: Share_Path
          value: "/share233"
