apiVersion: apps/v1
kind: Deployment
metadata:
  name: vtb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vtb
  template:
    metadata:
      labels:
        app: vtb
    spec:
      containers:
      - image: okteto.dev/vtb:latest
        name: vtb
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "7db75336-8f8f-4e58-a214-bf905d257d84"
        - name: Vless_Path
          value: "/u8on4s"
        - name: Vmess_UUID
          value: "7db75336-8f8f-4e58-a214-bf905d257d84"
        - name: Vmess_Path
          value: "/765fdvw34"
        - name: Share_Path
          value: "/share233"
