apiVersion: apps/v1
kind: Deployment
metadata:
  name: non
spec:
  replicas: 1
  selector:
    matchLabels:
      app: non
  template:
    metadata:
      labels:
        app: non
    spec:
      containers:
      - image: okteto.dev/non:latest
        name: non
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "5b241a44-c748-4192-a89c-f46d3fdb40dd"
        - name: Vless_Path
          value: "/5wfshqd2"
        - name: Vmess_UUID
          value: "5b241a44-c748-4192-a89c-f46d3fdb40dd"
        - name: Vmess_Path
          value: "/3efr25t"
        - name: Share_Path
          value: "/share233"
