apiVersion: apps/v1
kind: Deployment
metadata:
  name: vtb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vtb
  template:
    metadata:
      labels:
        app: vtb
    spec:
      containers:
      - image: okteto.dev/vtb:latest
        name: vtb
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "7fbaf195-8d19-4792-83fe-7a9b66907a68"
        - name: Vless_Path
          value: "/568yhnhki"
        - name: Vmess_UUID
          value: "7fbaf195-8d19-4792-83fe-7a9b66907a68"
        - name: Vmess_Path
          value: "/r7tujb465tg"
        - name: Share_Path
          value: "/share233"
