apiVersion: apps/v1
kind: Deployment
metadata:
  name: lme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lme
  template:
    metadata:
      labels:
        app: lme
    spec:
      containers:
      - image: okteto.dev/lme:latest
        name: lme
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "c2cc4c2d-c0fd-4cd2-bb13-1c317c052800"
        - name: Vless_Path
          value: "/679thwend"
        - name: Vmess_UUID
          value: "c2cc4c2d-c0fd-4cd2-bb13-1c317c052800"
        - name: Vmess_Path
          value: "/764efdew"
        - name: Share_Path
          value: "/share233"
