apiVersion: apps/v1
kind: Deployment
metadata:
  name: lg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lg
  template:
    metadata:
      labels:
        app: lg
    spec:
      containers:
      - image: okteto.dev/lg:latest
        name: lg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "971d93af-efb9-47ca-a8ab-e4d118d13a82"
        - name: Vless_Path
          value: "/83wejfd"
        - name: Vmess_UUID
          value: "971d93af-efb9-47ca-a8ab-e4d118d13a82"
        - name: Vmess_Path
          value: "/234rfs"
        - name: Share_Path
          value: "/share233"
