apiVersion: apps/v1
kind: Deployment
metadata:
  name: mate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mate
  template:
    metadata:
      labels:
        app: mate
    spec:
      containers:
      - image: okteto.dev/mate:latest
        name: mate
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "d298533c-6d0c-4b3b-b03d-c5db23899abb"
        - name: Vless_Path
          value: "/8ik34rwd"
        - name: Vmess_UUID
          value: "d298533c-6d0c-4b3b-b03d-c5db23899abb"
        - name: Vmess_Path
          value: "/76efdew53"
        - name: Share_Path
          value: "/share233"
