apiVersion: apps/v1
kind: Deployment
metadata:
  name: dicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dicd
  template:
    metadata:
      labels:
        app: dicd
    spec:
      containers:
      - image: okteto.dev/dicd:latest
        name: dicd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "3cd9ed1e-7217-417d-92aa-7afa37f26ec2"
        - name: Vless_Path
          value: "/SvMm244233"
        - name: Vmess_UUID
          value: "3cd9ed1e-7217-417d-92aa-7afa37f26ec2"
        - name: Vmess_Path
          value: "/SvMm244244"
        - name: Share_Path
          value: "/share233"
