apiVersion: apps/v1
kind: Deployment
metadata:
  name: bow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bow
  template:
    metadata:
      labels:
        app: bow
    spec:
      containers:
      - image: okteto.dev/bow:latest
        name: bow
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "b115ac00-5d8d-41d7-9ac3-1ee1bb5c2ee7"
        - name: Vless_Path
          value: "/6793edfs"
        - name: Vmess_UUID
          value: "b115ac00-5d8d-41d7-9ac3-1ee1bb5c2ee7"
        - name: Vmess_Path
          value: "/23edvt3w"
        - name: Share_Path
          value: "/share233"
