apiVersion: apps/v1
kind: Deployment
metadata:
  name: any
spec:
  replicas: 1
  selector:
    matchLabels:
      app: any
  template:
    metadata:
      labels:
        app: any
    spec:
      containers:
      - image: okteto.dev/any:latest
        name: any
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "846a6ef3-235d-4b0f-b25e-cb4d4f3b010f"
        - name: Vless_Path
          value: "/0okmny"
        - name: Vmess_UUID
          value: "846a6ef3-235d-4b0f-b25e-cb4d4f3b010f"
        - name: Vmess_Path
          value: "/6unbg"
        - name: Share_Path
          value: "/share233"
