apiVersion: apps/v1
kind: Deployment
metadata:
  name: voto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voto
  template:
    metadata:
      labels:
        app: voto
    spec:
      containers:
      - image: okteto.dev/voto:latest
        name: voto
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "82a05895-de28-46cd-8e2b-0f8f38c3a190"
        - name: Vless_Path
          value: "/Dyrnfs6"
        - name: Vmess_UUID
          value: "82a05895-de28-46cd-8e2b-0f8f38c3a190"
        - name: Vmess_Path
          value: "/Fu8met2"
        - name: Share_Path
          value: "/share233"
