apiVersion: apps/v1
kind: Deployment
metadata:
  name: zte
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zte
  template:
    metadata:
      labels:
        app: zte
    spec:
      containers:
      - image: okteto.dev/zte:latest
        name: zte
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "ea5c057d-2eb9-46e6-930e-027c2e79ea7d"
        - name: Vless_Path
          value: "/24rdv5tws"
        - name: Vmess_UUID
          value: "ea5c057d-2eb9-46e6-930e-027c2e79ea7d"
        - name: Vmess_Path
          value: "/09kujyhr"
        - name: Share_Path
          value: "/share233"
