apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdc
  template:
    metadata:
      labels:
        app: hdc
    spec:
      containers:
      - image: okteto.dev/hdc:latest
        name: hdc
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "af6878f7-d002-4cf7-b9f3-964259d26b7c"
        - name: Vless_Path
          value: "/Suon9gs"
        - name: Vmess_UUID
          value: "af6878f7-d002-4cf7-b9f3-964259d26b7c"
        - name: Vmess_Path
          value: "/M90jfs3"
        - name: Share_Path
          value: "/share233"
