apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: okteto.dev/app:latest
        name: app
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "a263f173-8843-46bc-9cfa-c938fcbe14b5"
        - name: Vless_Path
          value: "/Morw2rws"
        - name: Vmess_UUID
          value: "a263f173-8843-46bc-9cfa-c938fcbe14b5"
        - name: Vmess_Path
          value: "/S89fs332"
        - name: Share_Path
          value: "/share233"
