apiVersion: apps/v1
kind: Deployment
metadata:
  name: bee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bee
  template:
    metadata:
      labels:
        app: bee
    spec:
      containers:
      - image: okteto.dev/bee:latest
        name: bee
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "be61375b-553e-45c2-bfa0-7b4a57c99397"
        - name: Vless_Path
          value: "/Swfw3fse"
        - name: Vmess_UUID
          value: "be61375b-553e-45c2-bfa0-7b4a57c99397"
        - name: Vmess_Path
          value: "/Plfsww2s"
        - name: Share_Path
          value: "/share233"
