apiVersion: apps/v1
kind: Deployment
metadata:
  name: doov
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doov
  template:
    metadata:
      labels:
        app: doov
    spec:
      containers:
      - image: okteto.dev/doov:latest
        name: doov
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "21325332-6668-4b96-a027-a046cfd413b7"
        - name: Vless_Path
          value: "/nu89rfs"
        - name: Vmess_UUID
          value: "21325332-6668-4b96-a027-a046cfd413b7"
        - name: Vmess_Path
          value: "/64tefdf"
        - name: Share_Path
          value: "/share233"
