apiVersion: apps/v1
kind: Deployment
metadata:
  name: con
spec:
  replicas: 1
  selector:
    matchLabels:
      app: con
  template:
    metadata:
      labels:
        app: con
    spec:
      containers:
      - image: okteto.dev/con:latest
        name: con
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "ac0505ba-0eb3-47a5-835f-ffc2aed50d2c"
        - name: Vless_Path
          value: "/80ujgdlg"
        - name: Vmess_UUID
          value: "ac0505ba-0eb3-47a5-835f-ffc2aed50d2c"
        - name: Vmess_Path
          value: "/874etfd"
        - name: Share_Path
          value: "/share233"
