apiVersion: apps/v1
kind: Deployment
metadata:
  name: vivo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vivo
  template:
    metadata:
      labels:
        app: vivo
    spec:
      containers:
      - image: okteto.dev/vivo:latest
        name: vivo
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "d1eefea9-583e-4db7-8368-0d20b476118c"
        - name: Vless_Path
          value: "/yonr242465"
        - name: Vmess_UUID
          value: "d1eefea9-583e-4db7-8368-0d20b476118c"
        - name: Vmess_Path
          value: "/womef2f2332"
        - name: Share_Path
          value: "/share233"
