apiVersion: apps/v1
kind: Deployment
metadata:
  name: popo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: popo
  template:
    metadata:
      labels:
        app: popo
    spec:
      containers:
      - image: okteto.dev/popo:latest
        name: popo
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "88742f02-aa98-431d-baaf-f748434c46f7"
        - name: Vless_Path
          value: "/7irfsrfs2"
        - name: Vmess_UUID
          value: "88742f02-aa98-431d-baaf-f748434c46f7"
        - name: Vmess_Path
          value: "/54twefd"
        - name: Share_Path
          value: "/share233"
