apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcl
  template:
    metadata:
      labels:
        app: tcl
    spec:
      containers:
      - image: okteto.dev/tcl:latest
        name: tcl
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "96ae859e-be0c-41ab-9e4f-ac8b2efd08bc"
        - name: Vless_Path
          value: "/56yhb8yuh"
        - name: Vmess_UUID
          value: "96ae859e-be0c-41ab-9e4f-ac8b2efd08bc"
        - name: Vmess_Path
          value: "/34657gkj"
        - name: Share_Path
          value: "/share233"
