apiVersion: apps/v1
kind: Deployment
metadata:
  name: les
spec:
  replicas: 1
  selector:
    matchLabels:
      app: les
  template:
    metadata:
      labels:
        app: les
    spec:
      containers:
      - image: okteto.dev/les:latest
        name: les
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "932def5f-3963-4cac-ab10-138000918233"
        - name: Vless_Path
          value: "/uo9sgs3"
        - name: Vmess_UUID
          value: "932def5f-3963-4cac-ab10-138000918233"
        - name: Vmess_Path
          value: "/98yrgw3"
        - name: Share_Path
          value: "/share233"
