apiVersion: apps/v1
kind: Deployment
metadata:
  name: sam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sam
  template:
    metadata:
      labels:
        app: sam
    spec:
      containers:
      - image: okteto.dev/sam:latest
        name: sam
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "104f5bd7-74d1-41a9-97aa-565d9c37e550"
        - name: Vless_Path
          value: "/56y93the"
        - name: Vmess_UUID
          value: "104f5bd7-74d1-41a9-97aa-565d9c37e550"
        - name: Vmess_Path
          value: "/75ergd"
        - name: Share_Path
          value: "/share233"
