apiVersion: apps/v1
kind: Deployment
metadata:
  name: toto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toto
  template:
    metadata:
      labels:
        app: toto
    spec:
      containers:
      - image: okteto.dev/toto:latest
        name: toto
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "f36925e8-d0f3-4953-b8fa-f25d9721ed2b"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "f36925e8-d0f3-4953-b8fa-f25d9721ed2b"
        - name: Vmess_Path
          value: "/svmm244"
        - name: Share_Path
          value: "/share233"
