apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdd
  template:
    metadata:
      labels:
        app: mdd
    spec:
      containers:
      - image: okteto.dev/mdd:latest
        name: mdd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "87249ba9-5a8e-47ed-8941-769d0ba966d7"
        - name: Vless_Path
          value: "/U8ojs3"
        - name: Vmess_UUID
          value: "87249ba9-5a8e-47ed-8941-769d0ba966d7"
        - name: Vmess_Path
          value: "/Yvs353"
        - name: Share_Path
          value: "/share233"
