apiVersion: apps/v1
kind: Deployment
metadata:
  name: two
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two
  template:
    metadata:
      labels:
        app: two
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: two
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "f36925e8-d0f3-4953-b8fa-f25d9721ed2b"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "f36925e8-d0f3-4953-b8fa-f25d9721ed2b"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
