apiVersion: apps/v1
kind: Deployment
metadata:
  name: hot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hot
  template:
    metadata:
      labels:
        app: hot
    spec:
      containers:
      - image: okteto.dev/hot:latest
        name: hot
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "74767255-4403-4081-a9ab-c35e24c69a3d"
        - name: Vless_Path
          value: "/Bour5qf2"
        - name: Vmess_UUID
          value: "74767255-4403-4081-a9ab-c35e24c69a3d"
        - name: Vmess_Path
          value: "/V5wefd3"
        - name: Share_Path
          value: "/share233"
