apiVersion: apps/v1
kind: Deployment
metadata:
  name: now
spec:
  replicas: 1
  selector:
    matchLabels:
      app: now
  template:
    metadata:
      labels:
        app: now
    spec:
      containers:
      - image: okteto.dev/now:latest
        name: now
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "d7253a1e-b369-41af-b217-cdd134eb67f6"
        - name: Vless_Path
          value: "/9jfw3f"
        - name: Vmess_UUID
          value: "d7253a1e-b369-41af-b217-cdd134eb67f6"
        - name: Vmess_Path
          value: "/76trf3"
        - name: Share_Path
          value: "/share233"
