apiVersion: apps/v1
kind: Deployment
metadata:
  name: day
spec:
  replicas: 1
  selector:
    matchLabels:
      app: day
  template:
    metadata:
      labels:
        app: day
    spec:
      containers:
      - image: okteto.dev/day:latest
        name: day
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "173f770b-dfb5-4002-87c4-5d610f44c269"
        - name: Vless_Path
          value: "/8ujmkio"
        - name: Vmess_UUID
          value: "173f770b-dfb5-4002-87c4-5d610f44c269"
        - name: Vmess_Path
          value: "/5yhnbvt"
        - name: Share_Path
          value: "/share233"
