apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bsy
  template:
    metadata:
      labels:
        app: bsy
    spec:
      containers:
      - image: okteto.dev/bsy:latest
        name: bsy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "4c6d2eac-c92a-48d8-ac4b-8d14bdafc601"
        - name: Vless_Path
          value: "/7593rjef"
        - name: Vmess_UUID
          value: "4c6d2eac-c92a-48d8-ac4b-8d14bdafc601"
        - name: Vmess_Path
          value: "/876y5rd"
        - name: Share_Path
          value: "/share233"
