apiVersion: apps/v1
kind: Deployment
metadata:
  name: hua
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hua
  template:
    metadata:
      labels:
        app: hua
    spec:
      containers:
      - image: okteto.dev/hua:latest
        name: hua
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "2b1aca81-f667-43ca-983c-b46ada60a866"
        - name: Vless_Path
          value: "/6ujntw3w"
        - name: Vmess_UUID
          value: "2b1aca81-f667-43ca-983c-b46ada60a866"
        - name: Vmess_Path
          value: "/76t3weff3"
        - name: Share_Path
          value: "/share233"
