apiVersion: apps/v1
kind: Deployment
metadata:
  name: koo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koo
  template:
    metadata:
      labels:
        app: koo
    spec:
      containers:
      - image: okteto.dev/koo:latest
        name: koo
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "8081b222-00bb-4009-85f5-41326290737d"
        - name: Vless_Path
          value: "/0okmnj"
        - name: Vmess_UUID
          value: "8081b222-00bb-4009-85f5-41326290737d"
        - name: Vmess_Path
          value: "/7yerd"
        - name: Share_Path
          value: "/share233"
