apiVersion: apps/v1
kind: Deployment
metadata:
  name: like
spec:
  replicas: 1
  selector:
    matchLabels:
      app: like
  template:
    metadata:
      labels:
        app: like
    spec:
      containers:
      - image: okteto.dev/like:latest
        name: like
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "beauty-upgrade.tw"
        - name: Vless_UUID
          value: "4666ee1e-26e3-430a-98f0-3b340390ac46"
        - name: Vless_Path
          value: "/SvMm244233"
        - name: Vmess_UUID
          value: "4666ee1e-26e3-430a-98f0-3b340390ac46"
        - name: Vmess_Path
          value: "/SvMm244244"
        - name: Share_Path
          value: "/share233"
