apiVersion: apps/v1
kind: Deployment
metadata:
  name: boss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boss
  template:
    metadata:
      labels:
        app: boss
    spec:
      containers:
      - image: okteto.dev/boss:latest
        name: boss
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "2971e247-3b53-4acd-8372-f120323d4dc4"
        - name: Vless_Path
          value: "/SvMm244233"
        - name: Vmess_UUID
          value: "2971e247-3b53-4acd-8372-f120323d4dc4"
        - name: Vmess_Path
          value: "/SvMm244244"
        - name: Share_Path
          value: "/share233"
