apiVersion: apps/v1
kind: Deployment
metadata:
  name: cas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cas
  template:
    metadata:
      labels:
        app: cas
    spec:
      containers:
      - image: okteto.dev/cas:latest
        name: cas
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "8e6d1b60-fec8-4044-9293-a47defa759d7"
        - name: Vless_Path
          value: "/Jkorw2fs"
        - name: Vmess_UUID
          value: "8e6d1b60-fec8-4044-9293-a47defa759d7"
        - name: Vmess_Path
          value: "/Mor9wfs"
        - name: Share_Path
          value: "/share233"
